services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "8888:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Lab12345"
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql-scripts:/scripts
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Lab12345 -i /sql/ddl.sql &&
        wait"
    restart: unless-stopped
  
  lab1app:
    build:
      context: DotNetApplication/Lab1App/.
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  sql_data:
