services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "8888:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Lab12345"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data: